version: "3.8"

services:
  java:
    image: itzg/minecraft-server:java8
    # container_name: minecraft-java-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      TYPE: CURSEFORGE # CURSEFORGE or VANILLA
      VERSION: "1.12.2" # minecraft version
      FORGE_VERSION: "14.23.5.2860" # Forge version. Comment when vanilla
      CF_SERVER_MOD: /modpacks/SevTech_Ages_Server_3.2.3.zip # Modpack zip file. Comment when vanilla

      # optional
      WORLD: /worlds/world.zip

      # necessary for container to start
      EULA: "TRUE"
      MEMORY: "5G"
      INIT_MEMORY: "1G"
      RCON_PASSWORD: "minecraft"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./java-server:/data
      - ./modpacks:/modpacks:ro
      - ./worlds:/worlds:ro

volumes:
  java-server:
