version: "3.8"

services:
  java:
    image: itzg/minecraft-server
    container_name: minecraft-java-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
      INIT_MEMORY: "2G"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./java-server:/data
  
  win:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-bedrock-server
    tty: true
    stdin_open: true
    ports:
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
    volumes:
      - ./windows-server:/data

volumes:
  java-server:
  windows-server:
